FROM node:14 as build-stage
#ARG ENV_TYPE
WORKDIR /app
COPY package.json package-lock.json /app/
RUN npm cache clean --force
RUN npm install
#RUN npm install -g @angular/cli@11.2.4
COPY ./ /app/
#RUN ng build --prod
RUN npm run build
# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.15
RUN rm -rf /usr/share/nginx/html/*
#COPY --from=build-stage /app/dist/Perception-Web/ /usr/share/nginx/html
COPY --from=build-stage /app/dist/custom-theme/ /usr/share/nginx/html
# Copy the default nginx.conf provided by imonitor-frontend
COPY --from=build-stage /app/nginx.conf /etc/nginx/conf.d/default.conf
